### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by kelseyshaw** [ds4owd-001/md-02-assignments-kelseyshaw#1]
@larnsce @mianzg @sskorik01

**Comment by larnsce** [comment]
Thank you for working through the assignment @kelseyshaw. Could you double-check that you did the commit to track your changes and then also push to GitHub?

It’s Steps 2 & 3 as described on the website and also in the assignments itself: https://ds4owd-001.github.io/website/assignments/md-03/am-03-1-data-transformation.html#step-2-commit-and-push-your-changes

**Comment by kelseyshaw** [comment]
This should be updated now, thanks @larnsce !

**Comment by larnsce** [comment]
Yes, well done. I will close the issue for you now.
